/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive Github Webhook
         * @description Real production runs must never be silently dry-run: this is the one
         *     place `dry_run=False` is passed explicitly to `claim_fresh_run`, whose
         *     own signature has no default specifically so a caller can't forget.
         */
        post: operations["receive_github_webhook_webhooks_github_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runs Summary */
        get: operations["get_runs_summary_runs_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{owner}/{repo}/{issue_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Detail */
        get: operations["get_run_detail_runs__owner___repo___issue_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{owner}/{repo}/{issue_number}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace Summary */
        get: operations["get_trace_summary_runs__owner___repo___issue_number__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{owner}/{repo}/{issue_number}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pending Approval */
        get: operations["get_pending_approval_runs__owner___repo___issue_number__resume_get"];
        put?: never;
        /** Resume Run */
        post: operations["resume_run_runs__owner___repo___issue_number__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{owner}/{repo}/{issue_number}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Run */
        post: operations["retry_run_runs__owner___repo___issue_number__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionDecision
         * @description One human verdict on one queued action. `extra="forbid"` (inherited
         *     from `StrictBaseModel`) matters especially here: the resume value
         *     crosses a trust boundary (it's supplied by whatever external surface
         *     resumes the graph, not produced internally), so an unexpected field must
         *     be rejected rather than silently dropped.
         */
        ActionDecision: {
            /**
             * Index
             * @description Must match a `QueuedActionSummary.index` exactly.
             */
            index: number;
            /** Approved */
            approved: boolean;
            /**
             * Note
             * @description Optional reviewer note; recorded as `ActionPostResult.detail` on rejection.
             */
            note?: string | null;
        };
        /**
         * ActionPostResult
         * @description Persisted post-attempt outcome for one drafted action. Positional,
         *     not indexed: item i here always corresponds to `draft.actions[i]`,
         *     mirroring `ActionRiskAssessment`.
         */
        ActionPostResult: {
            outcome: components["schemas"]["PostOutcome"];
            /**
             * Detail
             * @description GitHub comment URL when a comment was actually POSTED; the created PR's URL when a POSTED code_fix became a pull request; the error message when FAILED; the reviewer's note (or None) when REJECTED; unused (None) for QUEUED or for a successful label/close (nothing distinct to point at).
             */
            detail?: string | null;
        };
        /**
         * ActionRiskAssessment
         * @description Persisted risk verdict for one drafted action. Positional, not
         *     indexed: item i here always assesses `draft.actions[i]`, mirroring every
         *     other per-item list in this schema layer (e.g. `DraftOutput.actions`
         *     itself).
         */
        ActionRiskAssessment: {
            level: components["schemas"]["RiskLevel"];
            /** Risk Factors */
            risk_factors?: string[];
            /** Reasoning */
            reasoning: string;
        };
        /**
         * ActionType
         * @enum {string}
         */
        ActionType: "comment" | "label" | "close" | "code_fix";
        /**
         * ApprovalDecision
         * @description The `Command(resume=...)` payload `ApprovalQueueNode` expects: one
         *     `ActionDecision` per queued action, no more, no fewer -- validated by
         *     the node itself, not by this model (index-set membership needs the
         *     queued indices, which aren't in scope here).
         */
        ApprovalDecision: {
            /** Decisions */
            decisions: components["schemas"]["ActionDecision"][];
        };
        /**
         * ApprovalRequest
         * @description The `interrupt()` payload `ApprovalQueueNode` surfaces -- one entry
         *     per queued action, requiring a matching `ActionDecision` on resume.
         *     Built by `ApprovalRequestBuilder`
         *     (`graph/nodes/utils/approval_request_builder.py`), not constructed
         *     directly by callers.
         */
        ApprovalRequest: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Repo Full Name */
            repo_full_name: string;
            /** Issue Number */
            issue_number: number;
            /** Issue Url */
            issue_url: string;
            /** Actions */
            actions: components["schemas"]["QueuedActionSummary"][];
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
        };
        /** CloseAction */
        CloseAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action_type: "close";
            /** Reason */
            reason: string;
            /** Close Comment */
            close_comment?: string | null;
        };
        /** CodeFixAction */
        CodeFixAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action_type: "code_fix";
            /** Diff */
            diff: string;
            /** Target Files */
            target_files: string[];
            sandbox_result: components["schemas"]["SandboxResult"];
            /** Base Commit Sha */
            base_commit_sha: string;
            /** Base Ref */
            base_ref: string;
        };
        /** CommentAction */
        CommentAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action_type: "comment";
            /** Comment Body */
            comment_body: string;
        };
        /**
         * DetailResponse
         * @description Generic `{"detail": ...}` body for a webhook delivery that didn't put
         *     a run in flight: an ignored event type, an ignored issue action, or a
         *     duplicate/already-in-progress redelivery.
         */
        DetailResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * DraftOutput
         * @description `unsupported_claims` comes from a second, independent LLM call (the
         *     grounding self-check, `DrafterSubgraph.grounding_check_node`) — never the
         *     same call that produced the draft, since a model grading its own
         *     unverified claims in the same breath it wrote them is a much weaker check
         *     than a second, independent pass over the finished draft plus the
         *     evidence.
         */
        DraftOutput: {
            /** Actions */
            actions: components["schemas"]["DraftedAction"][];
            /** Overall Rationale */
            overall_rationale: string;
            /** Unsupported Claims */
            unsupported_claims?: string[];
            /**
             * Drafted At
             * Format: date-time
             */
            drafted_at: string;
        };
        /**
         * DraftedAction
         * @description A persisted proposed action plus its rationale. `action` is typed as
         *     the full `DraftAction` union (including `CodeFixAction`) rather than
         *     `DraftIntent`, so this shape doesn't need to change when the sandbox
         *     code-fix path lands — it'll just start populating the `code_fix`
         *     variant that was always a valid member of this type.
         */
        DraftedAction: {
            /** Action */
            action: components["schemas"]["CommentAction"] | components["schemas"]["LabelAction"] | components["schemas"]["CloseAction"] | components["schemas"]["CodeFixAction"];
            /** Rationale */
            rationale: string;
        };
        /**
         * EpisodicActionOutcome
         * @description One past action plus what actually happened to it -- e.g. `comment`
         *     that was `posted`, or `code_fix` that was `rejected`. Positional
         *     correlation (action type <-> per-action outcome) is inherent here since
         *     each pair is built together, unlike `draft.actions`/`post_results.action_results`
         *     elsewhere in this codebase, which stay correlated by list index.
         */
        EpisodicActionOutcome: {
            action_type: components["schemas"]["ActionType"];
            outcome: components["schemas"]["PostOutcome"];
        };
        /** EpisodicMemoryHit */
        EpisodicMemoryHit: {
            /** Past Issue Number */
            past_issue_number: number;
            /** Past Repo */
            past_repo: string;
            /** Summary */
            summary: string;
            /** Actions Taken */
            actions_taken: components["schemas"]["EpisodicActionOutcome"][];
            outcome: components["schemas"]["RunStatus"];
            /** Similarity Score */
            similarity_score: number;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
        };
        /**
         * Evidence
         * @description One citation backing a research finding. `sha` is populated whenever
         *     the source naturally carries a git blob/commit SHA (GitHub commits/PRs,
         *     DocMind's codebase index) — that's the "SHA-stamped" traceability
         *     guarantee: a citation still points at the exact code/commit even if the
         *     file changes later. `None` for web results, or when a tool result
         *     doesn't expose one.
         */
        Evidence: {
            /** @description Which category of source this citation came from. */
            source_type: components["schemas"]["ResearchToolName"];
            /**
             * Reference
             * @description Where this came from, e.g. a file path, PR/issue URL.
             */
            reference: string;
            /**
             * Snippet
             * @description The relevant excerpt, verbatim from the source.
             */
            snippet: string;
            /**
             * Relevance
             * @description How directly this citation supports the summary, 0.0-1.0.
             */
            relevance: number;
            /**
             * Sha
             * @description Git blob/commit SHA, copied verbatim from the tool output.
             */
            sha?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IssueSource
         * @enum {string}
         */
        IssueSource: "webhook" | "replay";
        /**
         * IssueType
         * @enum {string}
         */
        IssueType: "bug" | "feature_request" | "question" | "documentation" | "duplicate" | "needs_more_info" | "spam_or_abuse" | "other";
        JsonValue: unknown;
        /** LabelAction */
        LabelAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action_type: "label";
            /** Labels To Add */
            labels_to_add?: string[];
            /** Labels To Remove */
            labels_to_remove?: string[];
        };
        /**
         * PlannerOutput
         * @description `classified_at` is a system-derived fact, not something asked of the
         *     LLM (models hallucinate timestamps) — the node constructs this itself
         *     from a `PlannerClassification` plus `datetime.now(UTC)`.
         */
        PlannerOutput: {
            issue_type: components["schemas"]["IssueType"];
            /** Classification Confidence */
            classification_confidence: number;
            /** Investigation Plan */
            investigation_plan?: string[];
            /** Reasoning */
            reasoning: string;
            /**
             * Classified At
             * Format: date-time
             */
            classified_at: string;
        };
        /**
         * PostOutcome
         * @enum {string}
         */
        PostOutcome: "posted" | "failed" | "queued" | "rejected";
        /**
         * PostResults
         * @description Persisted container -- the type of `TriageState.post_results`.
         *     `action_results` must be the same length as `draft.actions`, in the
         *     same order.
         */
        PostResults: {
            /** Action Results */
            action_results: components["schemas"]["ActionPostResult"][];
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
        };
        /**
         * QueuedActionSummary
         * @description One queued (non-LOW-risk) drafted action, rendered for human review.
         *     `index` is `draft.actions[index]`'s position -- the slot an
         *     `ActionDecision` in the resume payload targets. Fields below
         *     `risk_factors` are populated only for `action_type == "code_fix"`; all
         *     others carry `None`/`[]`.
         */
        QueuedActionSummary: {
            /** Index */
            index: number;
            action_type: components["schemas"]["ActionType"];
            /**
             * Summary
             * @description One-line, human-readable description of the action.
             */
            summary: string;
            /** Rationale */
            rationale: string;
            risk_level: components["schemas"]["RiskLevel"];
            /** Risk Reasoning */
            risk_reasoning: string;
            /** Risk Factors */
            risk_factors?: string[];
            /** Target Files */
            target_files?: string[];
            /** Sandbox Passed */
            sandbox_passed?: boolean | null;
            /** Sandbox Test Command */
            sandbox_test_command?: string | null;
            /**
             * Diff Preview
             * @description The unified diff, capped at 20000 UTF-8 bytes. The full diff is retained in run state regardless of truncation.
             */
            diff_preview?: string | null;
            /**
             * Diff Truncated
             * @default false
             */
            diff_truncated: boolean;
        };
        /**
         * ResearchFindings
         * @description Persisted research output. `tool_calls`/`tools_used`/`researched_at`
         *     are system-derived (see `ToolCallRecord`) rather than LLM-authored — the
         *     same two-stage split `PlannerOutput` uses over `PlannerClassification`.
         *
         *     `tools_used` is the actual tool *function* names invoked (e.g.
         *     `"search_code"`, `"list_commits"`) — not `ResearchToolName`: a single MCP
         *     server exposes many differently-named tools, so there's no clean
         *     many-to-one mapping down to "docmind"/"github"/"web". `Evidence.
         *     source_type` is the field that carries that higher-level categorization,
         *     as a judgment call the model itself makes per citation.
         */
        ResearchFindings: {
            /** Summary */
            summary: string;
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
            /** Focus Addressed */
            focus_addressed?: string[];
            /** Gaps */
            gaps?: string[];
            /** Confidence */
            confidence: number;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCallRecord"][];
            /** Tools Used */
            tools_used?: string[];
            /**
             * Researched At
             * Format: date-time
             */
            researched_at: string;
        };
        /**
         * ResearchToolName
         * @enum {string}
         */
        ResearchToolName: "docmind" | "github" | "web";
        /**
         * RetryRequest
         * @description Body for `POST /runs/{owner}/{repo}/{issue_number}/retry`. `dry_run`
         *     of `None` (the default -- omitted entirely is equivalent) means "reuse
         *     whatever `dry_run` the failed run itself used"; an explicit value
         *     overrides it.
         */
        RetryRequest: {
            /** Dry Run */
            dry_run?: boolean | null;
        };
        /**
         * RiskAssessment
         * @description Persisted container -- the type of `TriageState.risk_assessment`.
         *     `action_assessments` must be the same length as `draft.actions`, in the
         *     same order.
         */
        RiskAssessment: {
            /** Action Assessments */
            action_assessments: components["schemas"]["ActionRiskAssessment"][];
            /**
             * Assessed At
             * Format: date-time
             */
            assessed_at: string;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "low" | "medium" | "high";
        /**
         * RunAcceptedResponse
         * @description Response body for a run now in flight: a fresh webhook claim, a
         *     retry, or a resume, all scheduled as a background task and not yet
         *     finished. `run_id` is `None` for a resume -- unlike a fresh claim or a
         *     retry, resuming doesn't mint a new `run_id`, it continues the existing
         *     one. `status` reflects the run's actual current status rather than an
         *     invented ad hoc label: `RunStatus.RECEIVED` for a fresh claim/retry,
         *     `RunStatus.PENDING_APPROVAL` for a resume (per
         *     `repositories.triage_run_repository.TriageRunRepository.claim_resume`'s
         *     own docstring, `status` doesn't change value until the run settles).
         */
        RunAcceptedResponse: {
            /** Thread Id */
            thread_id: string;
            /** Run Id */
            run_id?: string | null;
            status: components["schemas"]["RunStatus"];
        };
        /**
         * RunDetailResponse
         * @description Full pipeline detail for a single run, backing `GET
         *     /runs/{owner}/{repo}/{issue_number}`. `run` is the same `RunSummary`
         *     projection the list endpoint uses; the pipeline fields below are
         *     `graph.schemas` domain models returned as-is (the same precedent the
         *     existing `/resume` route already sets for `ApprovalRequest`), and are
         *     `None` only in the narrow window between a webhook being accepted and
         *     the graph's first checkpoint superstep landing.
         */
        RunDetailResponse: {
            run: components["schemas"]["RunSummary"];
            planner_output: components["schemas"]["PlannerOutput"] | null;
            research_findings: components["schemas"]["ResearchFindings"] | null;
            draft: components["schemas"]["DraftOutput"] | null;
            risk_assessment: components["schemas"]["RiskAssessment"] | null;
            post_results: components["schemas"]["PostResults"] | null;
            /** Episodic Context */
            episodic_context: components["schemas"]["EpisodicMemoryHit"][];
            run_meta: components["schemas"]["RunMeta"] | null;
        };
        /** RunError */
        RunError: {
            /** Node Name */
            node_name: string;
            /** Error Message */
            error_message: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /**
         * RunListResponse
         * @description Page of `GET /runs`. `total`/`total_pages` are computed from the same
         *     filters as `items` (see `TriageRunRepository._list_filters`), so a
         *     frontend pager built from this response can never disagree with the
         *     rows it's paging over.
         */
        RunListResponse: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /** RunMeta */
        RunMeta: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Thread Id */
            thread_id: string;
            /** Trace Id */
            trace_id?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Iteration Count
             * @default 0
             */
            iteration_count: number;
            /**
             * Tool Calls Made
             * @default 0
             */
            tool_calls_made: number;
            /**
             * Estimated Cost Usd
             * @default 0
             */
            estimated_cost_usd: number;
            /**
             * Cache Read Tokens
             * @default 0
             */
            cache_read_tokens: number;
            /**
             * Cache Creation Tokens
             * @default 0
             */
            cache_creation_tokens: number;
            /** Max Iterations */
            max_iterations: number;
            /** Max Cost Usd */
            max_cost_usd: number;
            /** Errors */
            errors?: components["schemas"]["RunError"][];
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "received" | "planning" | "researching" | "drafting" | "risk_check" | "auto_posted" | "pending_approval" | "approved_and_posted" | "rejected" | "failed";
        /**
         * RunSummary
         * @description API-facing projection of a triage run -- deliberately decoupled from
         *     `TriageRunRecord` (the internal service/DB-mirroring DTO), so the public
         *     contract doesn't shift if an internal-only column is added, and internal
         *     fields (e.g. the `resume_in_progress` concurrency lock) never reach a
         *     client just because they exist on the ORM row.
         */
        RunSummary: {
            /** Thread Id */
            thread_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Repo Full Name */
            repo_full_name: string;
            /** Issue Number */
            issue_number: number;
            /** Issue Title */
            issue_title: string;
            /** Issue Url */
            issue_url: string;
            source: components["schemas"]["IssueSource"];
            status: components["schemas"]["RunStatus"];
            /** Retry Count */
            retry_count: number;
            /** Error Message */
            error_message: string | null;
            /** Dry Run */
            dry_run: boolean;
            /** Estimated Cost Usd */
            estimated_cost_usd: number | null;
            /** Duration Seconds */
            duration_seconds: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * RunSummaryResponse
         * @description Response body for `GET /runs/summary` -- the one endpoint for both
         *     current totals and trend data, no separate `/runs/trend`. `points` is
         *     always at least one element: a request with no `period` degenerates to
         *     a single all-time bucket (`interval=None`), which is exactly today's
         *     flat totals wrapped in a one-element list instead of returned bare.
         */
        RunSummaryResponse: {
            period: components["schemas"]["TimeRangePeriod"] | null;
            /** Interval */
            interval: ("minute" | "hour" | "day") | null;
            /** Points */
            points: components["schemas"]["TrendPoint"][];
        };
        /** SandboxResult */
        SandboxResult: {
            /** Passed */
            passed: boolean;
            /** Logs */
            logs: string;
            /** Test Command */
            test_command: string;
            /** Duration Seconds */
            duration_seconds: number;
        };
        /**
         * TimeRangePeriod
         * @enum {string}
         */
        TimeRangePeriod: "1h" | "24h" | "7d" | "30d";
        /**
         * ToolCallRecord
         * @description One tool invocation actually made during the research loop. Derived
         *     programmatically from the trajectory's `AIMessage.tool_calls` /
         *     `ToolMessage` pairs — never asked of the model, since self-reported
         *     bookkeeping is a hallucination risk the model has no reason to get
         *     exactly right.
         */
        ToolCallRecord: {
            /** Tool Name */
            tool_name: string;
            /** Arguments */
            arguments: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "error";
        };
        /**
         * TraceObservation
         * @description One Langfuse observation (span/generation/event/chain) within a
         *     trace, normalized from the raw camelCase-aliased SDK fields
         *     `observability.langfuse_reader.fetch_observations` returns (confirmed
         *     against the installed `langfuse` package's `ObservationV2` model).
         *
         *     `observation_type` is deliberately `str`, not a closed `Literal` --
         *     this pipeline's own traces contain `"CHAIN"` observations (the
         *     top-level LangGraph invocation, and each `AgentSubgraph` node) in
         *     addition to Langfuse's own `"SPAN"`/`"GENERATION"`/`"EVENT"` (see
         *     `evals/langfuse_fetch/reconstruct.py`'s own `"CHAIN"` matching) --
         *     render whatever string comes back rather than validating against an
         *     incomplete closed set.
         *
         *     `level` is optional -- the real SDK model's `level` field is itself
         *     optional, and `ObservationLevel` has four values (including `DEBUG`),
         *     not three.
         */
        TraceObservation: {
            /** Observation Id */
            observation_id: string;
            /** Parent Observation Id */
            parent_observation_id: string | null;
            /** Name */
            name: string | null;
            /** Observation Type */
            observation_type: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** End Time */
            end_time: string | null;
            /** Latency Seconds */
            latency_seconds: number | null;
            /** Cost Usd */
            cost_usd: number | null;
            /** Level */
            level: string | null;
        };
        /**
         * TraceSummaryResponse
         * @description Response body for `GET /runs/{owner}/{repo}/{issue_number}/trace` --
         *     an embedded per-node breakdown of one run's Langfuse trace, not a full
         *     interactive trace viewer (Langfuse's own hosted UI already does that
         *     far better than reproducing it here). `langfuse_url` is the escape
         *     hatch to that full UI.
         */
        TraceSummaryResponse: {
            /** Trace Id */
            trace_id: string;
            /** Langfuse Url */
            langfuse_url: string;
            /** Total Latency Seconds */
            total_latency_seconds: number | null;
            /** Total Cost Usd */
            total_cost_usd: number | null;
            /** Observations */
            observations: components["schemas"]["TraceObservation"][];
        };
        /**
         * TrendPoint
         * @description One bucket of `GET /runs/summary`'s time series. `bucket_start` is
         *     `None` only for the single all-time bucket a request with no `period`
         *     degenerates to; otherwise it's the start of an `interval`-width window.
         *     `counts_by_status` is zero-filled for every `RunStatus` value, same
         *     convention `RunSummaryResponse` used before this endpoint grew buckets,
         *     so a frontend never has to guard against a missing key.
         */
        TrendPoint: {
            /** Bucket Start */
            bucket_start: string | null;
            /** Counts By Status */
            counts_by_status: {
                [key: string]: number;
            };
            /** Run Count */
            run_count: number;
            /** Total Cost Usd */
            total_cost_usd: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    receive_github_webhook_webhooks_github_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAcceptedResponse"] | components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["RunStatus"][] | null;
                repo_full_name?: string | null;
                source?: components["schemas"]["IssueSource"] | null;
                period?: components["schemas"]["TimeRangePeriod"] | null;
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runs_summary_runs_summary_get: {
        parameters: {
            query?: {
                repo_full_name?: string | null;
                period?: components["schemas"]["TimeRangePeriod"] | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_detail_runs__owner___repo___issue_number__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                owner: string;
                repo: string;
                issue_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_summary_runs__owner___repo___issue_number__trace_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                owner: string;
                repo: string;
                issue_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pending_approval_runs__owner___repo___issue_number__resume_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                owner: string;
                repo: string;
                issue_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_runs__owner___repo___issue_number__resume_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                owner: string;
                repo: string;
                issue_number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_run_runs__owner___repo___issue_number__retry_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                owner: string;
                repo: string;
                issue_number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
